# Generated by Django 4.1.13 on 2025-11-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='device',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
